name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: sudo apt-get install build-essential autoconf autotools-dev pkg-config libsdl2-dev

    - name: autoreconf
      run: autoreconf -vfi

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check
