name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential autoconf autotools-dev pkg-config libsdl2-dev

    - name: autoreconf
      run: autoreconf -vfi

    - name: configure
      run: ./configure

    - name: make
      run: make -j6
